[WIP] refine lambda
projecteru2/core pull request #128
Opened 2019-08-28 11:28 UTC by jschwinger23

2019-08-29 17:04 UTC, CMGS requested changes

2019-08-29 17:04 UTC, CMGS commented on cluster/calcium/create.go
> +	config.Tty = opts.OpenStdin
不能复用 Stdin 属性么

2019-08-29 17:04 UTC, CMGS commented on cluster/calcium/lambda.go
> +		err := types.ErrRunAndWaitCountOneWithStdin
return nil, types.XXX

2019-08-29 17:04 UTC, CMGS commented on cluster/calcium/lambda.go
> +				outStream, err = node.Engine.VirtualizationLogs(ctx, message.ContainerID, true, true, true)
if xxx,err=xxx; err!= nil {}

2019-08-29 17:04 UTC, CMGS commented on cluster/calcium/lambda.go
> +			docker.ProcessVirtualizationInStream(ctx, inStream, inCh, specialPrefixCallback)
暴露了底层细节哇。。你这里得考虑抽象下，不然 VM 没法接了

2019-08-29 17:04 UTC, CMGS commented on engine/docker/helper.go
> +func ProcessVirtualizationOutStream(
我看在这里并不绑定 docker 哇

2019-08-30 11:37 UTC, jschwinger23 commented on engine/docker/helper.go
> +func ProcessVirtualizationOutStream(
移动到 calcium/helper.go 里了

2019-09-01 10:36 UTC, jschwinger23 commented
呃, 要先合入 core, 然后更新 go.mod, 然后才能通过 test, 然后才能合入...

2019-09-01 11:10 UTC, jschwinger23 commented
![](https://github.trello.services/images/mini-trello-icon.png) [exec 接口](https://trello.com/c/mI59DGfK/54-exec-%E6%8E%A5%E5%8F%A3)

2019-09-01 22:11 UTC, CMGS requested changes

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/execute.go
> +			processVirtualizationInStream(ctx, inStream, inCh, func(height, width uint) error {
看了下上下文，我觉得这可以把 go func 做成显式的

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/helper.go
> +				log.Errorf("[runAndWait] invalid winch command: %q", body)
[processVirtualizationInStream] not [runAndWait]

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/helper.go
> +					log.Debugf("special prefix matched: %q", cmd)
[rawProcessVirtualizationInStream] in logs

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/helper.go
> +					log.Errorf("failed to write virtual input stream: %v", err)
same here

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/helper.go
> +				_, err := inStream.Write([]byte{b})
if _,err:=xxx; err!= nil {
}

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/helper.go
> +				log.Errorf("[runAndWait] resize window error: %v", err)
same here

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/helper.go
> +) <-chan interface{} {
这个 done 似乎没用上？另外我倾向于标记 chan 用空 struct

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/helper.go
> +func processVirtualizationOutStream(
没理解错的话就是把输出变成最多 1K 一个的 buffer 呗对吧，所以上层 message 的 data 不以 \n 做分割咯

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/lambda.go
> +type window struct {
放到 helper 中

2019-09-01 22:11 UTC, CMGS commented on cluster/calcium/lambda.go
> +			outStream, inStream, err := node.Engine.VirtualizationAttach(ctx, message.ContainerID, true, true)
这里直接忽略了 OpenStdin 参数拿到了 out 和 in，为何后面还需要重新拿一次 logs？

2019-09-02 03:44 UTC, jschwinger23 commented on cluster/calcium/helper.go
> +func processVirtualizationOutStream(
嗯不以 \n 分割, 不能行缓冲, 收到什么都立刻吐出去

2019-09-02 03:46 UTC, jschwinger23 commented on cluster/calcium/lambda.go
> +			outStream, inStream, err := node.Engine.VirtualizationAttach(ctx, message.ContainerID, true, true)
for record: 
attach 拿不到之前的输出, log 有行缓冲, 所以不同的情况用不同的输出- -

2019-09-02 08:10 UTC, merged