[WIP] new engine interface: ExecuteAttach
projecteru2/core pull request #138
Opened 2019-09-29 09:02 UTC by jschwinger23

2019-09-30 02:36 UTC, CMGS commented on engine/engine.go
>  	ExecAttach(ctx context.Context, execID string, tty bool) (io.ReadCloser, io.WriteCloser, error)
那这个其实可以不保留了吧，把 resize 也整合进去？

2019-09-30 05:16 UTC, jschwinger23 commented
remind myself of bumping version due to change of interface

2019-10-04 07:34 UTC, CMGS requested changes

2019-10-04 07:34 UTC, CMGS commented on engine/docker/exec.go
> +
这个干脆叫 Execute 不行么。。。

2019-10-04 08:40 UTC, CMGS commented on engine/docker/exec.go
> +func (e *Engine) ExecuteAttach(ctx context.Context, target string, config *enginetypes.ExecConfig) (string, io.ReadCloser, io.WriteCloser, error) {
另外 Codacy 没过是因为这里作为一个 exported 的 method 没有对应的注释

2019-10-04 08:41 UTC, CMGS commented on engine/virt/virt.go
> +	} else {
按照逻辑来说，这里不需要有 else 了

2019-10-04 16:13 UTC, CMGS commented on engine/virt/virt.go
> +	return
而且这个 return 永远跑不到

2019-10-07 03:05 UTC, jschwinger23 commented on engine/virt/virt.go
> +	return
编译器报错啊, 说没有 return... 所以不用 else 就好了

2019-10-07 03:17 UTC, jschwinger23 commented on engine/engine.go
>  	ExecAttach(ctx context.Context, execID string, tty bool) (io.ReadCloser, io.WriteCloser, error)
按照 resize 的设计 https://trello.com/c/xaZ7RiUX/130-resize-vm-windows 搞不好还是需要 ExecID 这套机制....

2019-10-07 03:18 UTC, jschwinger23 commented
要等 libyavirt 合入后更新一下 dep 再

2019-10-07 03:20 UTC, CMGS commented on engine/engine.go
>  	ExecAttach(ctx context.Context, execID string, tty bool) (io.ReadCloser, io.WriteCloser, error)
好的

2019-10-07 04:04 UTC, merged