WIP: schedule volume resource
projecteru2/core pull request #161
Opened 2019-12-19 04:22 UTC by jschwinger23

2019-12-19 06:39 UTC, CMGS commented on Makefile
> -	cd ./rpc/gen/; python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. core.proto;
竟然抛弃了 python

2019-12-20 02:52 UTC, CMGS commented on cluster/calcium/node.go
> +	return c.store.AddNode(ctx, opts.Nodename, opts.Endpoint, opts.Podname, opts.Ca, opts.Cert, opts.Key, opts.Cpu, opts.Share, opts.Memory, opts.Storage, opts.Labels, opts.Numa, opts.NumaMemory, opts.V
要传这么多干脆就把 opts 丢进去吧

2019-12-20 02:58 UTC, jschwinger23 commented on cluster/calcium/node.go
> +	return c.store.AddNode(ctx, opts.Nodename, opts.Endpoint, opts.Podname, opts.Ca, opts.Cert, opts.Key, opts.Cpu, opts.Share, opts.Memory, opts.Storage, opts.Labels, opts.Numa, opts.NumaMemory, opts.V
好! (这不是懒得改接口嘛 (

2019-12-20 03:19 UTC, CMGS commented on cluster/calcium/resource.go
> +	nr.VolumePercent = float64(node.VolumeUsed) / float64(len(node.InitVolume))
这个分母怎么算的？对于 cpu 来说 len 是 cpu 个数，cpus 是个数的统计，如 10.5 个 CPU。对于 volumes 来说比如一个 dir:50G 用了 dir:10 G 你这个咋算，算 0.2 么？

2019-12-20 03:19 UTC, CMGS commented on rpc/transform.go
> +		r.Volume[volumeDir] = int(volumeCap)
我觉得你这里定义 nodeOptions 的时候应该给 int64，因为存的是 bytes，bytes 又很大

2019-12-20 03:19 UTC, CMGS commented on rpc/transform.go
> +	for volumeDir, volumeCap := range b.DeltaVolume {
既然都要这样不如封装一个函数

2019-12-20 03:19 UTC, CMGS commented on rpc/transform.go
> +		r.Volume[volumeDir] = int(volumeCap)
当然也不是说 int 不行，我记得是 32 或者 64 位，你确认下到底是多少这么用也行

2019-12-20 08:25 UTC, jschwinger23 commented on cluster/calcium/resource.go
> +	nr.VolumePercent = float64(node.VolumeUsed) / float64(len(node.InitVolume))
因为只对形如 `AUTO:$dst:rw:$size` 的请求进行调度分配, 所以一个节点上每个 device block 各自的 percentage 没啥意义, 就计算所有设备的 cap 总和作为分母...

所以一个节点假如有两个盘, 一个用了 10g/50g, 第二个用了 5g/100g, 总共的 percentage 就是 (10+5)/(50+100)

2019-12-20 08:26 UTC, jschwinger23 commented on rpc/transform.go
> +		r.Volume[volumeDir] = int(volumeCap)
我也想用 int64... 但是 CPUMap 里的类型写的 int, 我想复用类型...

go 里的 int 是 32 还是 64 取决于 OS 是 32bit 还是 64bit, 我姑且认为是 64bit 了,... 但确实不好

2019-12-20 08:42 UTC, CMGS commented on cluster/calcium/resource.go
> +	nr.VolumePercent = float64(node.VolumeUsed) / float64(len(node.InitVolume))
OK 可以

2019-12-20 08:42 UTC, CMGS commented on rpc/transform.go
> +		r.Volume[volumeDir] = int(volumeCap)
行8，那就先这样

2019-12-29 14:34 UTC, CMGS commented on utils/utils.go
> -func Min(x, y int) int {
我觉得你可以用递归。。。

2020-01-06 04:21 UTC, CMGS requested changes
另外你这个改动导致了大量测试覆盖率下降，得增加对 volume 分配和绑定的单元测试

2020-01-06 04:21 UTC, CMGS commented on cluster/calcium/create.go
> +							return c.store.UpdateNodeResource(ctx, node, m.CPU, opts.CPUQuota, opts.Memory, opts.Storage, m.VolumePlan.Consumed(), store.ActionIncr)
为啥不能就叫 Volume

2020-01-06 04:21 UTC, CMGS commented on scheduler/complex/potassium.go
> +		if len(segs) < 4 || segs[0] != "AUTO" {
AUTO 应该是常量

2020-01-06 04:21 UTC, CMGS commented on types/options.go
> +	Cpu        int
CPU

2020-01-06 04:21 UTC, CMGS commented on types/options.go
> +type AddNodeOptions struct {
加注释才能 export

2020-01-06 04:21 UTC, CMGS commented on scheduler/complex/potassium.go
> +func (m *Potassium) SelectVolumeNodes(nodesInfo []types.NodeInfo, volumeReqs []string) ([]types.NodeInfo, map[string][]types.VolumePlan, int, error) {
加注释才能 export

2020-01-06 04:28 UTC, CMGS commented on types/node.go
> +		volumeMap.Add(v)
reuse volumMap.Consumed

2020-01-06 08:36 UTC, jschwinger23 commented on utils/utils.go
> -func Min(x, y int) int {
改啦

2020-01-06 08:38 UTC, jschwinger23 commented on cluster/calcium/create.go
> +							return c.store.UpdateNodeResource(ctx, node, m.CPU, opts.CPUQuota, opts.Memory, opts.Storage, m.VolumePlan.Consumed(), store.ActionIncr)
VolumePlan 的数据结构是`volume 请求` 与 `实际分配的 volumeMap` 的映射, 比如
`{"AUTO:/data:rw:100": VolumeMap{"/device": 100}`

2020-01-06 08:45 UTC, jschwinger23 commented on cluster/calcium/create.go
> +							return c.store.UpdateNodeResource(ctx, node, m.CPU, opts.CPUQuota, opts.Memory, opts.Storage, m.VolumePlan.Consumed(), store.ActionIncr)
VolumePlan 会作为 Container 的新增字段存到 store, 也会作为 create container 的返回新增到 pb.CreateContainerMessage 里, 这样对于资源的管理就没啥问题, 在删除容器的时候通过 VolumePlan 就能知道实际调度的资源

2020-01-06 08:45 UTC, jschwinger23 commented on scheduler/complex/potassium.go
> +func (m *Potassium) SelectVolumeNodes(nodesInfo []types.NodeInfo, volumeReqs []string) ([]types.NodeInfo, map[string][]types.VolumePlan, int, error) {
这个放心啦, 最后会过 lint 的

2020-01-07 07:31 UTC, CMGS commented on types/node.go
> +func (p VolumePlan) GetVolumeString(autoVolume string) (volume string) {
写得这么拧巴
```golang
volume = autoVolume
if volumeMap, ok := p[autoVolume]; ok {
		volume = strings.Replace(autoVolume, "AUTO", volumeMap.GetResourceId(), 1)
}
return
```

2020-01-07 09:22 UTC, CMGS commented on cluster/calcium/helper.go
> +	for _, vol := range volumes2 {
这 2 个 for 可以合并成 1 个

2020-01-08 04:02 UTC, CMGS commented on types/node.go
> +func ToVolumePlan(plan map[string]map[string]int64) VolumePlan {
lint 又要叫了，而且这个函数放在这里不太合适吧，utils 里面？

2020-01-09 02:45 UTC, CMGS commented on cluster/calcium/realloc.go
>  // cpu:memory
// val:cpu:memory

2020-01-09 03:16 UTC, jschwinger23 commented on types/node.go
> +func ToVolumePlan(plan map[string]map[string]int64) VolumePlan {
放到 utils/utils.go 里就循环引用了...  core/types -> core/utils -> core/cluster -> core/types ....

2020-01-09 03:22 UTC, jschwinger23 commented
all checks passed lah!

2020-01-09 04:11 UTC, CMGS commented on scheduler/complex/potassium.go
> +		req = append(req, int64(size))
不需要 int64

2020-01-09 06:22 UTC, anrs commented on cluster/calcium/helper.go
> +	sizeMap := map[string]int64{} // {"AUTO:/data:rw": 100}
// "AUTO:/data:rw:100" => {"AUTO:/data:rw": 100}

2020-01-09 07:03 UTC, jschwinger23 commented on rpc/transform.go
> +		if len(parts) != 4 || parts[0] == types.AUTO {
@anrs 这里我感觉不对, 有什么建议吗

2020-01-10 03:16 UTC, jschwinger23 commented
![](https://github.trello.services/images/mini-trello-icon.png) [支持 bind device](https://trello.com/c/3Ubw7Gss/151-%E6%94%AF%E6%8C%81-bind-device)

2020-01-10 04:28 UTC, CMGS commented on engine/docker/container.go
> +		log.Warnf("[VirtualizationUpdateResource] docker engine not support rebinding volume resource: %v", opts.Volumes)
如果是 warn 的话，但资源会被扣掉吧

2020-01-10 05:52 UTC, jschwinger23 commented on engine/docker/container.go
> +		log.Warnf("[VirtualizationUpdateResource] docker engine not support rebinding volume resource: %v", opts.Volumes)
嗯. 考虑这样的情况, 创建容器时用的请求是 `--volumes AUTO:/data:rw:1G`, 之后再 realloc 的时候, 就算 realloc 请求里没有 volume, realloc 也会重新调度磁盘(当然会调度到相同的盘), `VirtualizationUpdateResource` 也会收到有 `VolumePlan` 的 opt, 我们不能让它失败啊.

2020-01-10 06:18 UTC, CMGS commented on engine/docker/container.go
> +		log.Warnf("[VirtualizationUpdateResource] docker engine not support rebinding volume resource: %v", opts.Volumes)
那你得加个判断，是否真的是没申请 realloc volume，这一点上和 CPU 的分配还是有点区别的

2020-01-10 06:44 UTC, jschwinger23 commented on engine/docker/container.go
> +		log.Warnf("[VirtualizationUpdateResource] docker engine not support rebinding volume resource: %v", opts.Volumes)
好,  那我在 `enginetypes.VirtualizationResource` 里加一个字段, 因为只有 calcium 才能知道是否 re-volume 了, 而 engine 层只有一个 ID.... 倒是可以再 inspect 一下或者怎么着, 没必要.

2020-01-10 06:46 UTC, CMGS commented on engine/docker/container.go
> +		log.Warnf("[VirtualizationUpdateResource] docker engine not support rebinding volume resource: %v", opts.Volumes)
恩，这样比较合理，减少重复计算的过程和造成接口二义性

2020-01-13 04:47 UTC, jschwinger23 commented on cluster/calcium/helper.go
> +			VolumeUsed:   float64(node.VolumeUsed) / float64(len(node.InitVolume)),
错的

2020-01-13 06:50 UTC, jschwinger23 commented on utils/utils.go
> +	return len(s1) - len(s2)
fault...

2020-01-14 02:45 UTC, CMGS approved these changes

2020-01-14 02:45 UTC, merged