[WIP] cpu bind affinity during realloc
projecteru2/core pull request #293
Opened 2020-12-10 07:18 UTC by jschwinger23

2020-12-15 17:26 UTC, jschwinger23 commented
有一个地方需要讨论, 是完整核调度优先, 还是核亲和优先.

case: 已存在的容器的 cpu map: `{"0": 50}`, 当前节点可用的 cpu map: `{"0":40, "1":100}`, 请求 quota=1, cpubind=keep, 希望的调度结果是 `{"0":90, "1":10}` 还是 `{"1":100}`?

调度结果 1 是亲和优先, 保证了依然在 0 号 cpu 上, 但是是碎片; 调度结果 2 是完整核优先, 结果是完整核, 但是不亲和了.

当前 PR 是完整核优先调度.

@CMGS

2020-12-15 17:29 UTC, CMGS commented
> 有一个地方需要讨论, 是完整核调度优先, 还是亲和优先.
> 
> case: 已存在的容器的 cpu map: `{"0": 50}`, 当前节点可用的 cpu map: `{"0":40, "1":100}`, realloc 请求 quota=1, cpubind=keep, 希望的调度结果是 `{"0":90, "1":10}` 还是 `{"1":100}`?
> 
> 调度结果 1 是亲和优先, 保证了依然在 0 号 cpu 上, 但是是碎片; 调度结果 2 是完整核优先, 结果是完整核, 但是不亲和了.
> 
> 当前 PR 是完整核优先调度.
> 
> @CMGS

完整核优先，因为理论上 0:90 1:10 在 docker 中压根就支持不了

2020-12-16 06:56 UTC, jschwinger23 commented
逼迫自己把覆盖率从 99.0% 提升到 99.1%, 结果还真是这个没覆盖到的地方出现了 bug....

2020-12-16 17:33 UTC, CMGS requested changes

2020-12-16 17:33 UTC, CMGS commented on types/resource.go
> +	CPUMapExist     map[string]CPUMap
ResourceOptions 不叫 CPUMapExist ，对于 Resource 而言只有 CPU

2020-12-16 17:33 UTC, CMGS commented on utils/utils.go
> +// Min64 return lesser one
没测试吧，覆盖率下降了

2020-12-16 17:33 UTC, CMGS commented on scheduler/scheduler.go
> +	SelectCPUNodes(scheduleInfos []resourcetypes.ScheduleInfo, quota float64, memory int64, existCPUInfo map[string]types.CPUMap) ([]resourcetypes.ScheduleInfo, map[string][]types.CPUMap, int, error)
同理这里换我就叫 CPU map[string]types.CPUMap, 唉为啥会是 map[string]

2020-12-17 02:20 UTC, jschwinger23 commented on scheduler/scheduler.go
> +	SelectCPUNodes(scheduleInfos []resourcetypes.ScheduleInfo, quota float64, memory int64, existCPUInfo map[string]types.CPUMap) ([]resourcetypes.ScheduleInfo, map[string][]types.CPUMap, int, error)
其实信息量等价于元组 (nodename, CPUMap), 又不想拆成两个变量, 就用 map[string]CPUMap 了

2020-12-17 02:24 UTC, CMGS commented on scheduler/scheduler.go
> +	SelectCPUNodes(scheduleInfos []resourcetypes.ScheduleInfo, quota float64, memory int64, existCPUInfo map[string]types.CPUMap) ([]resourcetypes.ScheduleInfo, map[string][]types.CPUMap, int, error)
恩这个我懂，但实际上这个 map 里面就只有一个 key 吧

2020-12-17 02:34 UTC, jschwinger23 commented on scheduler/scheduler.go
> +	SelectCPUNodes(scheduleInfos []resourcetypes.ScheduleInfo, quota float64, memory int64, existCPUInfo map[string]types.CPUMap) ([]resourcetypes.ScheduleInfo, map[string][]types.CPUMap, int, error)
嗯, 有什么好建议吗

2020-12-17 07:55 UTC, CMGS commented on scheduler/scheduler.go
> +	SelectCPUNodes(scheduleInfos []resourcetypes.ScheduleInfo, quota float64, memory int64, existCPUInfo map[string]types.CPUMap) ([]resourcetypes.ScheduleInfo, map[string][]types.CPUMap, int, error)
如果是我的话，我会加个 ReSelectCPUNodes

2020-12-17 07:56 UTC, CMGS commented on scheduler/scheduler.go
> +	SelectCPUNodes(scheduleInfos []resourcetypes.ScheduleInfo, quota float64, memory int64, existCPUInfo map[string]types.CPUMap) ([]resourcetypes.ScheduleInfo, map[string][]types.CPUMap, int, error)
或者类似的

2020-12-17 08:01 UTC, jschwinger23 commented on scheduler/scheduler.go
> +	SelectCPUNodes(scheduleInfos []resourcetypes.ScheduleInfo, quota float64, memory int64, existCPUInfo map[string]types.CPUMap) ([]resourcetypes.ScheduleInfo, map[string][]types.CPUMap, int, error)
好

2020-12-18 17:59 UTC, CMGS approved these changes

2020-12-18 18:08 UTC, merged