Resource Plugin
projecteru2/core pull request #491
Opened 2021-10-15 04:21 UTC by DuodenumL

关于资源插件化的PR。

设计想法：对于core来说，它不需要知道各种资源的作用&分配方式，只需要把请求的参数转发给资源插件即可。资源插件会进行资源的具体分配工作，并对core返回engine args，用于后续engine层创建workload。

资源插件采用可执行文件的方式，core会加载指定目录下的所有可执行文件作为资源插件。

在创建workload的流程中，eru-cli要把所有关于资源的请求参数转化为map[string][]string的形式，例如{"cpu": ["1.2"]}。由于core不知道哪些参数对应哪个资源插件，所以它会把所有的参数依次转发给所有的资源插件。各个插件自己负责解析自己需要的参数，并做出正确的处理。

由于要实现插件化，所以资源相关的信息并不会再存储在node metadata里了，而是由各个资源插件自己负责存储，存储也不一定用ETCD，处理得当的话MySQL / MongoDB之类的也行（就是部署麻烦点）。

因此在workload metadata中，关于资源的描述换成了map[string]map[string][]string的方式（是不是看着有点绕），例如：
```
{
  "cpu-plugin": {
    "cpu": ["1.2"],
    "file": ["some-file"]
  },
  "mem-plugin": {
    "mem": ["1PB"],
    "file": ["some-other-file"]
  }
}
```

要分别记录各个资源插件分配的资源，否则在rollback / remove要释放资源的时候不知道怎么释放。

主要要做的事情：
- 把当前资源处理的逻辑改成插件的形式。
- cluster层和engine层要基于resource args的改动做出变化。

2021-10-15 04:25 UTC, DuodenumL commented
针对当前commit的一些说明：
- cluster/calcalcium就是“使用资源插件的calcium”，为了防止混乱复制出来一份，不然IDE一顿报错难顶。这里大部分的文件没啥改动，主要就是在create.go及与其关联的其它文件上有变动。
- PluginManager目前还没抽象化，但是Plugin做成了Interface。先撸实现再优化吧...

2021-10-15 07:08 UTC, CMGS commented
所以我应该看哪些- -

2021-10-15 07:16 UTC, DuodenumL commented
> 所以我应该看哪些- -

现在完成度还没那么高，主要动的是
- calcalium/create.go以及这里面调用到的各种东西
- resources/plugin.go + manager.go

2021-10-15 08:53 UTC, jschwinger233 reviewed
整体方向还行, 就是有些实现有点别扭, 现在先不用在意.

2021-10-15 08:53 UTC, jschwinger233 commented on resources/manager.go
> +				Rate:     info1.Rate + info2.Rate*info2.Weight,
加权平均

2021-10-15 08:53 UTC, jschwinger233 commented on resources/plugin.go
> +	GetAvailableNodes(ctx context.Context, rawRequest RawParams) (map[string]*types.NodeResourceInfo, int, error)
名字不好, 之后换一个.

2021-10-15 09:37 UTC, DuodenumL commented on resources/manager.go
> +				Rate:     info1.Rate + info2.Rate*info2.Weight,
这里是加权平均，L134的是当前带加权的总和，最后会除以总数来算平均

2021-10-15 09:37 UTC, DuodenumL commented on resources/plugin.go
> +	GetAvailableNodes(ctx context.Context, rawRequest RawParams) (map[string]*types.NodeResourceInfo, int, error)
There are only two hard things in Computer Science...

2021-10-18 03:22 UTC, CMGS commented on utils/file.go
> +	entries, err := os.ReadDir(path)
filepath.Walk 轻松重构

2021-10-18 03:32 UTC, CMGS commented on types/resource.go
> +type ResourcePluginOptions map[string][]string
interface map 呢

2021-10-18 03:38 UTC, CMGS commented on types/options.go
> +	ResourceOpts   ResourcePluginOptions
为啥不叫 ResourceOptions

2021-10-29 09:49 UTC, DuodenumL commented
纪念一下，终于能build了...下一步是把cpu和mem先写成插件，持续debug

2021-10-29 09:52 UTC, DuodenumL commented on cluster/calcium/build.go
> +	node := nodes[0]
标记一下，这里还得改改...

计划是让每个plugin都实现max idle node，并且返回一个优先级，选择优先级最大的那个node。

实际操作的时候只有cpu插件返回比较大的优先级。

2021-10-29 10:17 UTC, DuodenumL commented on resources/plugin.go
> +	LockNodes(ctx context.Context, nodes []string) error
这里也是有点纠结，感觉插件这边不一定需要有lock的功能，依赖core里那个ETCD的锁也不是不行？

2021-11-02 03:27 UTC, CMGS requested changes

2021-11-02 03:27 UTC, CMGS commented on core.go
> +		// todo: http.Handle("/metrics", metrics.Client.ResourceMiddleware(cluster)(promhttp.Handler()))
这是做啥

2021-11-02 03:27 UTC, CMGS commented on utils/transaction.go
> +func PCR(ctx context.Context, prepare func() error, commit func() error, rollback func() error) error {
按照之前的风格也应该叫 `Pcr`

2021-11-02 03:27 UTC, CMGS commented on utils/transaction.go
> +	err := prepare()
`if err := prepare(); err != nil { bla bla } ` 紧凑点

2021-11-02 03:27 UTC, CMGS commented on utils/transaction.go
> +	err = commit()
同样这里也是，风格保持一致

2021-11-02 03:27 UTC, CMGS commented on utils/transaction.go
> +	return nil
而且按照这个注释写的逻辑，我感觉其实用 Txn 包一下就可以了啊

2021-11-02 03:27 UTC, CMGS commented on utils/transaction.go
> +	return nil
类似于 if prepare then commit else rollback，为什么需要一个新函数

2021-11-02 03:27 UTC, CMGS commented on utils/file_test.go
> +	files, err := ListAllExecutableFiles("/usr/bin")
不要硬编码，你可以用 tempfile 生成临时文件，另外不要用 Println，在 test 里面是毫无意义的

2021-11-02 03:27 UTC, CMGS commented on types/node.go
> +		// todo: resource args
记录 todo 用大写，这样你在搜索 TODO 的时候能全匹配到

2021-11-02 03:27 UTC, CMGS commented on types/node.go
> +		// todo: resource args
另外这里为啥是 todo

2021-11-02 03:27 UTC, CMGS commented on types/message.go
> +type RawParams map[string]interface{}
这个放 message 合适么

2021-11-02 03:27 UTC, CMGS commented on types/config.go
> +	ResourcePluginDir     string        `yaml:"resource_plugin_dir" default:"/etc/eru/resource_plugins"` // resource plugins path
Plugins，注意是复数

2021-11-02 03:27 UTC, CMGS commented on types/config.go
> +	ResourcePluginDir     string        `yaml:"resource_plugin_dir" default:"/etc/eru/resource_plugins"` // resource plugins path
另外折腾了这里的话，你的 yaml sample 也得改

2021-11-02 03:27 UTC, CMGS commented on metrics/metrics.go
> +//
WTF？

2021-11-02 03:27 UTC, CMGS commented on metrics/handler.go
> +//func (m *Metrics) ResourceMiddleware(cluster cluster.Cluster) func(http.Handler) http.Handler {
WTF？？

2021-11-02 03:27 UTC, CMGS commented on lock/mocks/template.go
> +	m.On("Lock", mock.Anything).Return(context.Background(), nil)
这是用在哪里的，既不是测试又不是 mock？

2021-11-02 03:27 UTC, CMGS commented on engine/transform.go
> +	err = json.Unmarshal(body, &res)
紧凑点

2021-11-02 03:28 UTC, DuodenumL commented on core.go
> +		// todo: http.Handle("/metrics", metrics.Client.ResourceMiddleware(cluster)(promhttp.Handler()))
metrics里删了一大堆东西，后续也许还要补上，这里放一个todo...

2021-11-02 03:30 UTC, DuodenumL commented on utils/transaction.go
> +	return nil
其实是完全可以用Txn来替换的，用这个PCR主要是为了体现Prepare过程是无副作用的，这样感觉逻辑清晰一些...

目前的设计里plugin的大部分API都是纯计算无副作用的，例如Alloc / Realloc / Remap，它们就适用于Prepare过程

2021-11-02 03:33 UTC, DuodenumL commented on metrics/metrics.go
> +//
因为Node里的ResourceMeta也换成map[string]interface{}了，所以不能直接用之前这个metrics，这里等流程跑通了之后要改...

2021-11-02 03:34 UTC, DuodenumL commented on lock/mocks/template.go
> +	m.On("Lock", mock.Anything).Return(context.Background(), nil)
这个是store的FromTemplate里调用的...

2021-11-02 03:35 UTC, DuodenumL commented on utils/file_test.go
> +	files, err := ListAllExecutableFiles("/usr/bin")
嗯嗯，这里放了个TODO，后续写单测的时候会换成合理的实现

2021-11-02 03:37 UTC, DuodenumL commented on types/node.go
> +		// todo: resource args
metrics里关于resource的部分都暂时阉割掉了，后续应该还要恢复回来，所以是一个todo...

2021-11-02 03:39 UTC, DuodenumL commented on utils/file_test.go
> +	files, err := ListAllExecutableFiles("/usr/bin")
现在这里是我自己本地运行着看的哈哈...= =

2021-11-02 07:14 UTC, CMGS commented on utils/file.go
> +	return files, nil
```
files := []string{}
	if err := filepath.Walk(basedir, func(path string, info fs.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() && path != basedir {
			return filepath.SkipDir
		}
		if isExecutable(info.Mode().Perm()) {
			files = append(files, path)
		}
		return nil
	}); err!= nil {
        return nil, err
    }
```

可以写紧凑点的

2021-11-10 09:11 UTC, jschwinger233 requested changes

2021-11-10 09:11 UTC, jschwinger233 commented on rpc/gen/core.proto
> +  repeated string slice = 1;
好像没有必要单独定义这个 message

2021-11-10 09:11 UTC, jschwinger233 commented on resources/plugin.go
> +	UpdateNodeResourceCapacity(ctx context.Context, node string, resourceOpts coretypes.RawParams, direction bool) error
`node` 这个名字不好, 这个仓库里 node 变量都是 *types.Node 类型, string 类型的变量名是 nodename

2021-11-10 09:11 UTC, jschwinger233 commented on resources/manager.go
> +			close(rollbackPluginChan)
rollbackPluginChan 听起来像是要回滚的 plugin, 但是 len()==all 的时候又不回滚, 这个逻辑虽然正确但是很奇怪, 想办法调整一下

2021-11-10 09:11 UTC, jschwinger233 commented on resources/manager.go
> +			close(rollbackPluginChan)
我终于知道这里哪里最别扭了, 是你把 fan-out fan-in 的逻辑的一部分放到 callPlugins 里, 而这个拆分的结果是, 如你在当前这一层来观察 rollbackPluginChan 这个 chan, 你会发现没有并发场景去使用它, 但是如果改成 []Plugin slice 也不对, 因为并发被 callPlugins 藏起来的, 但是必要的并发同步却又留给了调用方.
我觉得这里可以使用泛型了, callPlugins[T any](xxx, func(Plugin) T) []T, 让 callPlugin 内部的 goroutine 完成所有的同步, 最后返回 slice.

2021-11-10 09:11 UTC, jschwinger233 commented on resources/plugin.go
> +	LockNodes(ctx context.Context, nodes []string) error
这个已经讨论过了, 先依然用 core 的锁, 如果有什么问题再来讨论

2021-11-10 09:11 UTC, jschwinger233 commented on resources/plugin.go
> +	SelectAvailableNodes(ctx context.Context, nodes []string, resourceOpts coretypes.RawParams) (map[string]*types.NodeResourceInfo, int, error)
声明类型的时候, 对那些读上去不知道是啥的最好加上变量名增加可读性, 比如这里的返回值 (map, int, error) 可以写成 (_ map, variableName int, _ error), 可以让人知道这个 int 是啥, 这样注释都可以直接省略

2021-11-10 09:11 UTC, jschwinger233 commented on resources/plugin.go
> +	GetNodeResourceInfo(ctx context.Context, node string, workloads []*coretypes.Workload, fix bool) (coretypes.RawParams, coretypes.RawParams, []string, error)
这个接口拆两个吧, Get 操作的同时在改数据...

2021-11-10 09:11 UTC, jschwinger233 commented on resources/plugin.go
> +	SetNodeResourceInfo(ctx context.Context, resourceCapacity coretypes.RawParams, resourceUsage coretypes.RawParams) error
这个接口第三参数是 resourceUsage, 和 UpdateNodeResourceUsage 这个接口是不是语义重复了

2021-11-10 09:11 UTC, jschwinger233 commented on resources/plugin.go
> +	Alloc(ctx context.Context, node string, deployCount int, resourceOpts coretypes.RawParams) ([]coretypes.RawParams, []coretypes.RawParams, error)
没看懂前两个 return 值是啥, 不如你把变量名加到返回值的类型声明里; RawParam 这个类型是只和资源有关的吗? 从名字来看像是能承载外物

2021-11-10 09:11 UTC, jschwinger233 commented on resources/plugin.go
> +	SetNodeResourceInfo(ctx context.Context, resourceCapacity coretypes.RawParams, resourceUsage coretypes.RawParams) error
还有 UpdateNodeResourceCapacity, 功能重复?

2021-11-10 09:11 UTC, jschwinger233 commented on resources/plugin.go
> +	AddNode(ctx context.Context, node string, resourceOpts coretypes.RawParams) (coretypes.RawParams, coretypes.RawParams, error)
第二返回值是啥

2021-11-10 10:22 UTC, jschwinger233 requested changes
感觉还是 callPlugins 太恶心了, 改成泛型就好了

2021-11-10 10:22 UTC, jschwinger233 commented on resources/plugin.go
> +	UpdateNodeResourceUsage(ctx context.Context, node string, resourceArgs []coretypes.RawParams, direction bool) error
direction 是啥?

2021-11-10 10:22 UTC, jschwinger233 commented on resources/manager.go
> +func (pm *PluginManager) SelectAvailableNodes(ctx context.Context, nodes []string, resourceOpts types.RawParams) (map[string]*resourcetypes.NodeResourceInfo, int, error) {
doCalculateCapacity 和 SelectAvailableNodes 这两个函数几乎拥有一样的语义吧, 我觉得前者的名字好一点, 然后似乎不需要 doCalculateCapacity 这个函数了

2021-11-10 10:22 UTC, jschwinger233 commented on resources/manager.go
> +func (pm *PluginManager) Alloc(ctx context.Context, node string, deployCount int, resourceOpts types.RawParams) ([]types.RawParams, []map[string]types.RawParams, error) {
pm.Alloc 是有 IO 的而 plugin.Alloc 是纯计算的, 最好统一一下 Alloc 这个函数的语义

2021-11-10 10:41 UTC, jschwinger233 reviewed
有个问题, 我们对命令行接口好像有点理解不同, 我心想的其实是那种..以文档 spec 来规定接口的命令行, 比如 https://github.com/containernetworking/cni/blob/master/SPEC.md#cni-operations, spec 规定一个正确的实现应该有哪些命令行调用选项, 最后的实现方只要提供一个二进制满足 spec 就好; 
但是你的接口好像是让 plugin 去实现一个 golang interface?

2021-11-10 10:41 UTC, jschwinger233 commented on cluster/calcium/create.go
> +func (c *Calcium) doDeployWorkloadsOnNode(ctx context.Context, ch chan *types.CreateWorkloadMessage, nodename string, opts *types.DeployOptions, deploy int, engineArgs []types.RawParams, resourceArgs
这个参数太多了, 手动格式化一下, 一个参数一行

2021-11-10 10:41 UTC, jschwinger233 commented on engine/transform.go
> +	if err = json.Unmarshal(body, &res); err != nil {
聪明!

2021-11-10 10:41 UTC, jschwinger233 commented on resources/plugin.go
> +		log.Errorf(ctx, "[callBinaryPlugin] failed to run plugin %s, command %s %v, err %s", bp.path, cmd, args, err)
这里 err 的时候输出一下 stderr, 非常有帮助

2021-11-10 10:45 UTC, jschwinger233 commented
cluster 层的逻辑整体方向没太大问题, plugin 那里需要再讨论一下, 我可以直接看看你实现的一个具体的 plugin 仓库先.
不过还有很多实现细节要打磨.

2021-11-11 04:36 UTC, DuodenumL commented on resources/plugin.go
> +	SetNodeResourceInfo(ctx context.Context, resourceCapacity coretypes.RawParams, resourceUsage coretypes.RawParams) error
这里的Set是设置绝对值，Update用的是相对值...

2021-11-11 04:38 UTC, DuodenumL commented on resources/plugin.go
> +	GetNodeResourceInfo(ctx context.Context, node string, workloads []*coretypes.Workload, fix bool) (coretypes.RawParams, coretypes.RawParams, []string, error)
大力支持！之前的Get我就觉得有点奇怪...

2021-11-11 04:39 UTC, DuodenumL commented on resources/plugin.go
> +	Alloc(ctx context.Context, node string, deployCount int, resourceOpts coretypes.RawParams) ([]coretypes.RawParams, []coretypes.RawParams, error)
打算把RawParams改成具体的类型，WorkloadResourceOpts / NodeResourceOpts / WorkloadResourceArgs / NodeResourceArgs / EngineArgs

2021-11-11 04:40 UTC, DuodenumL commented on resources/plugin.go
> +	AddNode(ctx context.Context, node string, resourceOpts coretypes.RawParams) (coretypes.RawParams, coretypes.RawParams, error)
resource usage

2021-11-11 04:42 UTC, DuodenumL commented on resources/plugin.go
> +	UpdateNodeResourceUsage(ctx context.Context, node string, resourceArgs []coretypes.RawParams, direction bool) error
Incr / Decr，表示usage的改变方向

2021-11-11 04:50 UTC, DuodenumL commented on resources/manager.go
> +func (pm *PluginManager) Alloc(ctx context.Context, node string, deployCount int, resourceOpts types.RawParams) ([]types.RawParams, []map[string]types.RawParams, error) {
不只是Alloc，为了方便回滚 + PCR，plugin里大多数func都是纯计算的...但是在plugin manager里为了方便外部调用，就成了有IO的。

如果plugin的Alloc也有IO，那么plugin manager回滚的时候就不能统一调用UpdateNodeResourceUsage，而是要反向调用Alloc，也就是说Alloc本身要提供rollback的能力，感觉这样就啰嗦了很多。

*当然不可以在plugin manager里将所有resource args取反向然后直接UpdateNodeResourceUsage，因为默认core这边是不知道如何计算“反向”的，而且不是所有resource args都能通过加个负号就变成“反向”的。

所以这里的解决方案...可能是把plugin里的Alloc改成一个看起来无副作用的名字？

2021-11-11 04:51 UTC, DuodenumL commented on cluster/calcium/create.go
> +func (c *Calcium) doDeployWorkloadsOnNode(ctx context.Context, ch chan *types.CreateWorkloadMessage, nodename string, opts *types.DeployOptions, deploy int, engineArgs []types.RawParams, resourceArgs
借个楼，最终实现的时候是“提供一个二进制满足spec”的，plugin这个interface一方面是为了mock，一方面是“万一以后用rpc插件呢？”

2021-11-11 07:27 UTC, jschwinger233 commented on cluster/calcium/create.go
> +func (c *Calcium) doDeployWorkloadsOnNode(ctx context.Context, ch chan *types.CreateWorkloadMessage, nodename string, opts *types.DeployOptions, deploy int, engineArgs []types.RawParams, resourceArgs
我对这个 go interface 没意见, 我是看到你没有实现具体的命令行调用方式, 如果按照 spec 来调用, 那么命令行的调用方式都是一样的, 只需要换二进制.

2021-11-11 07:41 UTC, jschwinger233 commented on resources/plugin.go
> +	UpdateNodeResourceUsage(ctx context.Context, node string, resourceArgs []coretypes.RawParams, direction bool) error
那把这个类型建立一个 alias 吧, 不要用 bool, 语义模糊

2021-11-29 10:16 UTC, DuodenumL commented
用泛型重写了一下plugin manager，显著减少了编码过程的痛苦。但是现在各种工具对泛型的支持还不全，包括但并不限于：

- Goland识别不出来[T any]里这个any，试了下VSCode也不太行
- Goland还有各种奇奇怪怪的报错，比如说会提示`func() int`不能匹配`func() T`
- mockery在Parse的过程中会报错，看了下现在mockery自己还在用go1.16。
- go vet在泛型的地方会报错，导致go test的时候还要手动指定一下`-vet=off`。
- golangci-lint跟mockery有一样的问题。

mockery这个问题我想办法解决了：要pull下来mockery的代码，然后把go版本改成1.17，在go install的时候要这么用：`go install -gcflags=all=-G=3 -tags="typeparams"。但是golangci-lint还没搞...

2021-11-30 08:00 UTC, DuodenumL commented
现在的Plugin API设计是完全基于之前代码里的需求（以及为了具体实现的方便）设计出来的，而不是从头思考”一个resource plugin应该做什么“。这也导致里面有一些奇奇怪怪的smell。比如：

- 为了方便回滚，plugin的Alloc是纯计算，这看起来跟Alloc的语义不太搭。plugin manager里的那个Alloc真正负责了计算+回滚，这个才合理一些。Realloc也是一样。
- `GetNodeCapacity`看起来有点像`GetNodeResourceCapacity`的意思，实际上这个是用来计算能部署多少个workload的。
- 虽然Plugin API里把`GetNodeResourceInfo` / `FixNodeResource`拆开了，但是最后到cpumem的实现里还是放一起的，用法是`cpumem get-node --node xxx --fix`，不加`--fix`就是普通的get。感觉白拆了。
- `UpdateNodeResourceCapacity`和`UpdateNodeResourceUsage`看起来像是行为类似的API，但是二者的参数一个是`NodeResourceOpts`，一个是`[]WorkloadResourceArgs`。
- `SetNodeResourceInfo`的存在完全只是为了给RemoveNode做回滚，看起来跟`UpdateNodeResourceCapacity`和`UpdateNodeResourceUsage`功能上似乎有冲突。（实际上不同，set是absolute，update是delta）


用这套API去实现的时候也遇到了一些暂时没法解决的问题。比如：

- `eru-cli node set`是可以指定使用delta还是absolute的，但是`UpdateNodeResourceCapacity`只能用delta。
- NUMA信息是resource capacity呢？还是resource usage呢？还是独立于这两者的呢？目前cpumem的实现是把它放在了resource capacity里，但是这导致`UpdateNodeResourceCapacity`有点难做，因为从用户使用的角度来看，不应该在设置资源的时候以delta的形式设置NUMA。举个例子，原来是32个核心，分成4个numa node。后来一看奥看错了我只有16个核，那这个时候改起来就比较痛苦。（不太现实的例子，实际这种需求应该也比较低频，只是用来说明delta不合理。）


所以应该考虑重新设计一套更合理的API，设计好了后续的工作就可以快速推进。cpumem那边基础的工作已经做好了，即使API变了改起来也是很快的。

2021-12-03 10:51 UTC, jschwinger233 requested changes
主要 review 了 create 流程, Alloc 那部分可能要再推敲一下.
用了泛型后确实好多了.

2021-12-03 10:51 UTC, jschwinger233 commented on cluster/calcium/create.go
> +	resourceArgsMap := map[string][]map[string]types.WorkloadResourceArgs{}
这两句变量初始化放到下面两行 var ( xx ) 一起吧

2021-12-03 10:51 UTC, jschwinger233 commented on cluster/calcium/create.go
> +					deployMap, err = c.doGetDeployMap(ctx, nodes, opts)
这个函数的定义再精细一点, 传入的 opts 信息冗余了, 其实里面只用到了 opts.ResourceOpts, .Name, .Entrypoint.Name, 等; 里面调用的 strategy.Deploy 也一样, 传入的参数信息冗余了, 尽量只传入需要的值.

2021-12-03 10:51 UTC, jschwinger233 commented on resources/manager.go
> +func callPlugins[T any](plugins []Plugin, f func(Plugin) (T, error)) (results map[Plugin]T) {
感觉 error 还是要显示抛出来? 看你里面是直接扔掉了 err, 虽然之后你通过 len() 来判断有没有出错, 但是报错信息丢失了反映不出是什么问题

2021-12-03 10:51 UTC, jschwinger233 commented on resources/manager.go
> +			log.Errorf(ctx, "[GetNodesCapacity] plugin %v failed to get available nodeNames, request %v, err %v", plugin.Name(), resourceOpts, err)
接上面关于 callPlugins 的 error 的讨论, 把 err log 统一放到 callPlugins 里吧

2021-12-03 10:51 UTC, jschwinger233 commented on resources/plugin.go
> +func (bp *BinaryPlugin) getArgs(req interface{}) []string {
丧心病狂! 但是好像确实只能这么做.

2021-12-03 10:51 UTC, jschwinger233 commented on resources/manager.go
> +			return nil
rollback nil 的话好像没必要用 util.Pcr

2021-12-03 10:51 UTC, jschwinger233 commented on resources/manager.go
> +	return utils.Pcr(ctx,
这里的事务是不是有问题, 你的写法是: 
prepare: 做一些初始化
do: 做资源扣减
undo: 回滚资源扣减
但是 Pcr 的语义是回滚 prepare; 具体来说, 假设你的 do 里的资源扣减失败了(没有扣减成功), 那么就会触发 undo 回滚扣减, 那么会导致可用资源的增加.

2021-12-03 10:51 UTC, jschwinger233 commented on resources/manager.go
> +	return utils.Pcr(ctx,
Pcr 的语义是回滚 prepare, 也就是说, prepare 产生了一些副作用, 接着如果 do 失败, 需要回滚 prepare 产生的副作用.

2021-12-03 10:51 UTC, jschwinger233 commented on resources/manager.go
> +				resp, err := plugin.Alloc(ctx, nodeName, deployCount, resourceOpts)
Alloc 的语义是啥来着, 一个纯计算返回  engineArgs 的接口吗? 是不是让 Alloc 这个名字留给一个 IO / 有副作用的操作比较好, 你看 malloc(1)

2021-12-03 10:51 UTC, jschwinger233 commented on cluster/calcium/create.go
> +						engineArgsMap[node], resourceArgsMap[node], err = c.resource.Alloc(ctx, node, deploy, opts.ResourceOpts)
c.resource 其实是 plugin manager, 换个不那么各应的名字吧

2021-12-03 10:51 UTC, jschwinger233 commented on cluster/calcium/create.go
> +						return errors.WithStack(err)
这里不要 errors.WithStack,  因为是从 c.doGetDeployMap 里抛出来的, 在那里面的 err 出现的地方包上 WithStack

2021-12-03 10:55 UTC, jschwinger233 commented
你提出的 API 设计上的问题我再想想.

2022-02-16 07:43 UTC, DuodenumL commented
把cpumem插件的内存版实现放上去了。接下来仍然要做的事情：
1. volume插件（这个插件负责volume和storage）
2. zc指出，在cluster层的改动需要注意函数原有的语义，比如资源的分配和回滚要在同一层级进行
3. AddNode支持自动设置
4. metrics（这个难搞）
5. 单元测试
6. 迁移脚本 / 回滚脚本

2022-03-24 11:13 UTC, DuodenumL commented
现在别的都已经做完，只需要做一下迁移脚本了，可以开始review了 @CMGS @jschwinger233

2022-03-25 07:20 UTC, DuodenumL commented
golangci-lint在指定go1.18时会自动禁用一些linter，最终导致nolintlint过不了。暂时把nolintlint给disable了。

2022-03-27 17:46 UTC, CMGS commented on utils/file.go
> +func isExecutable(perm fs.FileMode) bool {
private 的放后面

2022-03-27 17:47 UTC, CMGS commented on utils/file.go
> +const executablePerm = 0111
const 能整理下么

2022-03-27 17:48 UTC, CMGS commented on utils/generics.go
> +func Map[T1, T2 any](slice []T1, f func(T1) T2) []T2 {
太骚了，测试加起来，这部分一看 ut 的覆盖率急剧下降了

2022-03-27 17:48 UTC, CMGS commented on utils/ram.go
> +	flag := int64(1)
测试 too

2022-03-27 17:49 UTC, CMGS commented on utils/transaction.go
> +func Pcr(ctx context.Context, prepare func(ctx context.Context) error, commit func(ctx context.Context) error, rollback func(ctx context.Context) error, ttl time.Duration) error {
缩写用 PCR

2022-03-27 17:51 UTC, CMGS commented on types/resource.go
> +// StringSlice .
unit test

2022-03-30 10:40 UTC, DuodenumL commented
迁移工具 & 回滚工具做好啦

2022-04-06 08:10 UTC, jschwinger233 reviewed
整体结构还行, 兼容性可能要考虑再改改.

2022-04-06 08:10 UTC, jschwinger233 commented on rpc/gen/core.proto
> +  ResourceOptions old_resource_opts = 24;
这个就不兼容了吧, 一升级就把客户端升挂了.

2022-04-06 08:10 UTC, jschwinger233 commented on cluster/calcium/realloc.go
> +			engineArgs, deltaResourceArgs, resourceArgs, err = c.resource.Realloc(ctx, workload.Nodename, workload.ResourceArgs, opts.ResourceOpts)
这里的 txn 有没有可能做得对称一点, 比如这里用 source.SetNodeResourceUsage + store.UpdateWorkload 来回滚 resource.Realloc, 语义是非常隐晦的, 最好是有对称的 API.

2022-04-06 08:47 UTC, DuodenumL commented on cluster/calcium/realloc.go
> +			engineArgs, deltaResourceArgs, resourceArgs, err = c.resource.Realloc(ctx, workload.Nodename, workload.ResourceArgs, opts.ResourceOpts)
其实应该理解为Realloc的回滚是resource.SetNodeResourceUsage，store.UpdateWorkload回滚的是上面的store.UpdateWorkload，算是一一对应的，就是Realloc回滚这里名字不大对称...

2022-04-06 09:59 UTC, DuodenumL commented on cluster/calcium/realloc.go
> +			engineArgs, deltaResourceArgs, resourceArgs, err = c.resource.Realloc(ctx, workload.Nodename, workload.ResourceArgs, opts.ResourceOpts)
manager里把realloc和alloc的rollback包了一下，这样看起来就是对称的了。

2022-04-11 03:29 UTC, jschwinger233 approved these changes

2022-04-14 07:54 UTC, DuodenumL commented
准备合啦，接下来的工作都要基于插件化来做了。

2022-04-14 07:57 UTC, merged