[SPVR-141] Implement imagePush and buildRefs
projecteru2/core pull request #509
Opened 2021-11-30 02:20 UTC by Aceralon

* Implement imagePush and buildRefs for vm
* Return imgID in buildFromExist
* Add detailed warning log
* Add mock command for API

2021-11-30 04:35 UTC, jschwinger233 requested changes

2021-11-30 04:35 UTC, jschwinger233 commented on cluster/calcium/build.go
> +		return nil, nil, errors.WithStack(err)
这里不 errors.WithStack, 只在层和层的交界处包 stack, 或者是自己创造出来的 error

2021-11-30 04:35 UTC, jschwinger233 commented on cluster/calcium/build.go
> +		return nil, nil, errors.WithStack(err)
所谓层和层的交接, 比如 cluster 层和 engine 层

2021-11-30 04:35 UTC, jschwinger233 commented on cluster/calcium/build.go
> +		return nil, nil, errors.WithStack(err)
所以这里的 with stack 是对的

2021-11-30 04:35 UTC, jschwinger233 commented on cluster/calcium/helper.go
> +func toBuildRefOptions(opts *types.BuildOptions) *enginetypes.BuildRefOptions {
你真想要这个函数, 也不应该放在 helper.go, 而是 build.go 里

2021-11-30 06:04 UTC, Aceralon commented on cluster/calcium/build.go
> +		return nil, nil, errors.WithStack(err)
done

2021-11-30 07:33 UTC, jschwinger233 commented on cluster/calcium/build.go
> +		return nil, nil, err
- -  这里需要 with stack

2021-11-30 07:37 UTC, Aceralon commented on cluster/calcium/build.go
> +		return nil, nil, err
. ok

2021-12-01 09:19 UTC, jschwinger233 approved these changes

2021-12-01 09:19 UTC, merged