fix: keep the node status when a running node is bypassed
projecteru2/core pull request #517
Opened 2021-12-17 09:48 UTC by DuodenumL

场景：一个node被设置了bypass，但是我们只希望它不参与后续的部署，node上面的workloads还可以正常提供服务。

问题：agent启动后更新了node status，selfmon收到了变更信息，调用SetNode，打算把这个node设置成UP。但是因为它被bypass了，所以触发了n.IsDown()，node status又被删除。selfmon再次收到变更信息，然后调用SetNode把node设置为DOWN，并且将上面所有workload标记为not running。

修复：修改一下判断条件，只有在非bypass且down的情况才会删除node status。

2021-12-17 10:03 UTC, jschwinger233 commented
下周来讨论一下 selfmon 的设计问题, 这里你先仔细测试我们的场景, bypass=true && available=true 的时候对上面容器的影响, etcdctl watch 一下 status key 看看 put 的数据对不对.

2021-12-17 13:15 UTC, jschwinger233 commented on cluster/calcium/node.go
> +		if !n.Bypass && !n.Available {
bypass && available: 节点正常, 不允许部署
!bypass && available: 节点正常, 允许部署
bypass && !available: 节点不正常, 不允许部署
!bypass && !available:  节点不正常, 允许部署

所以这里的条件改成了"节点不正常, 允许部署", 这时候去删除 node status, 好像语义上解释不通?

2021-12-17 13:21 UTC, jschwinger233 commented on store/etcdv3/meta/etcd.go
> +		log.Infof(ctx, "[bindStatusWithoutTTL] put: key %s value %s", statusKey, statusValue)
其实 err == nil 的时候不一定是 put 了数据, 要判断一下 resp, 在有几个分支里是没有 put io 的.

2021-12-17 13:25 UTC, jschwinger233 requested changes
十五字

2021-12-17 13:31 UTC, jschwinger233 commented on cluster/calcium/node.go
> +					log.Errorf(ctx, "[SetNodeAvailable] Set workload %s on node %s as inactive failed %v", workload.ID, opts.Nodename, err)
WithStack(err)

2021-12-18 07:30 UTC, DuodenumL commented on cluster/calcium/node.go
> +		if !n.Bypass && !n.Available {
应该是!n.Available的时候就删掉node status，这样比较合理，selfmon就可以把真正not running的node上所有workload标记为not running了。我测一下看有没有问题。

2021-12-20 04:33 UTC, DuodenumL commented
在BindStatus里ETCD产生PUT的条件分支都打了log，以后debug起来方便些。

同时修复了之前BindStatus并没有处理TTL变更的情况。

举个例子，在value没变的情况下，以前ttl=10，新来了个请求ttl=5，最终的ttl还是为10。类似地，ttl=10没法变成ttl=0，ttl=0的也没法变成ttl=10。这个影响面不大，只在手动调用set-status的时候才会出问题，不过还是顺手给改了。

2021-12-20 04:33 UTC, DuodenumL commented
还有一个遗留问题是BindStatusWithoutTTL里并没有判断entity是否存在，不清楚加上之后会不会有奇怪的后果，所以我没敢加...

2021-12-20 06:44 UTC, jschwinger233 requested changes

2021-12-20 06:44 UTC, jschwinger233 commented on store/etcdv3/meta/etcd.go
> +// isTTLChanged returns true iff there is a lease with the same ttl bound to the key
iff -> if

2021-12-20 06:44 UTC, jschwinger233 commented on store/etcdv3/meta/etcd.go
> +// isTTLChanged returns true iff there is a lease with the same ttl bound to the key
这个函数名叫 TTLChanged, 正常的语义应该是 return true if ttl changed 才对吧

2021-12-20 06:44 UTC, jschwinger233 commented on store/etcdv3/meta/etcd.go
> +			return false, nil
没有 key 的时候可以算是 ttl changed 吧, 因为 ttl changed 的后续流程是直接 put k v with lease, 没有 key 直接 put 就好了.

2021-12-20 07:49 UTC, DuodenumL commented on store/etcdv3/meta/etcd.go
> +// isTTLChanged returns true iff there is a lease with the same ttl bound to the key
这里iff是"if and only if"，设计的目的是“当且仅当这个key已经有lease而且ttl不同时返回true”（没有Lease就不算ttl changed），所以我后半句写反了...

结合下面那个评论，想了一下即使没有key直接put应该也不会出现奇怪情况，我改一下

2021-12-20 08:57 UTC, jschwinger233 commented on cluster/calcium/node.go
> +		if !n.Bypass && !n.Available {
我测了一下发现好像每次 agent set status 都会导致 core put 一次 etcd, 好像是有问题?

2021-12-20 09:15 UTC, jschwinger233 approved these changes

2021-12-20 09:19 UTC, merged