Add send large file from cli
projecteru2/core pull request #532
Opened 2022-01-07 09:09 UTC by lianghongji

关于cli的send命令，之前的`send`是直接整个文件发到core里面，但是core的grpc配置为单条message最大只能为20M，所以有些文件是无法传输到core端的。

这里是增加了一个叫做`SendLargeFile`的方法，用`stream`的方式接受cli端分`chunk`发送过来的数据，并拼接起来再一并发送到容器里面。

2022-01-07 09:16 UTC, jschwinger233 requested changes

2022-01-07 09:16 UTC, jschwinger233 commented on rpc/rpc.go
> +		fileDetails.Data[metaData.Dst] = append(fileDetails.Data[metaData.Dst], chunk.Data...)
不应该全部读到内存, 而是流式传入 v.cluster.Send, 最终是 append 到一个 tar 文件里, 然后调用 docker api 发送过去

2022-01-07 09:24 UTC, jschwinger233 commented on rpc/rpc.go
> +		fileDetails.Data[metaData.Dst] = append(fileDetails.Data[metaData.Dst], chunk.Data...)
甚至可能不必等所有内容 append tar, 因为 docker api 本身也是流式的: `CopyToContainer(ctx context.Context, container, path string, content io.Reader, options types.CopyToContainerOptions)`.

2022-01-12 14:58 UTC, lianghongji commented on rpc/rpc.go
> +		fileDetails.Data[metaData.Dst] = append(fileDetails.Data[metaData.Dst], chunk.Data...)
我想准备用`io.Pipe()`来解决这个问题，这个方法会返回两个接口，`io.Reader`和`io.Writer`，这里的`io.Writer`对象可以放进`tar.NewWriter(io.Writer)`的参数里面，然后流式的写入，然后`io.Reader`对象可以放进`CopyToContainer(ctx context.Context, container, path string, content io.Reader, options types.CopyToContainerOptions) `里面。

然后目前遇到的问题是这样，我现在在Cluster层能拿到API层通过channel传过来的file chunk数据，然后构造出了上面说的`io.Writer`和`io.Reader`，这时候我是需要把`io.Reader`对象传给Engine的。但是问题在于我们在Engine层的接口定义是这样：`VirtualizationCopyTo(ctx context.Context, ID, target string, content []byte, uid, gid int, mode int64) error`，参数是`[]byte`，那我能有的做法我想是这样：

1. 新增一个VirtualizationCopyChunkTo方法，参数把[]byte改成io.reader里面就简单的调用docker的接口，没有其他的逻辑，但是这么做的话就需要改其他Engine的实现了（虽然我看virt也是需要一个io.Reader）
2. 在cluster层把chunk拼接起来，然后调用VirtualizationCopyTo方法，沿用以前的逻辑，让他去构造temp tar file，这样的话就不需要用到io.Pipe()了，但是会需要在Cluster层做文件的拼接。

大佬认为哪种方案会好一些？

2022-01-13 02:45 UTC, jschwinger233 commented on rpc/rpc.go
> +		fileDetails.Data[metaData.Dst] = append(fileDetails.Data[metaData.Dst], chunk.Data...)
把 []byte 改成 io.Reader

2022-01-19 07:17 UTC, jschwinger233 requested changes

2022-01-19 07:17 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +func (c *Calcium) SendLargeFile(ctx context.Context, opts chan *types.SendLargeFileOptions, resp chan *types.SendMessage) error {
resp chan 应该作为函数返回的参数

2022-01-19 07:17 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +		logrus.Debugf("[SendLargeFile] send to the end")
用 logger

2022-01-19 07:17 UTC, jschwinger233 commented on cluster/cluster.go
> +	SendLargeFile(ctx context.Context, opts chan *types.SendLargeFileOptions, resp chan *types.SendMessage) error
其实不用加新的 interface, 直接改旧的 Send 就可以了.

2022-01-19 07:17 UTC, jschwinger233 commented on rpc/gen/core.proto
> +        repeated string ids = 1;
这个 ids 是 workload ids 吧, 不应该放在 MetaData 里, 应该放在外面一层

2022-01-19 07:17 UTC, jschwinger233 commented on rpc/gen/core.proto
> +    message Chunk {
其实感觉没有必要做这层封装, 直接定义 bytes chunk 这个字段就好了

2022-01-19 07:17 UTC, jschwinger233 commented on rpc/rpc.go
> +	utils.SentryGo(func(ctx context.Context, opts chan *types.SendLargeFileOptions, resp chan *types.SendMessage) func() {
这里的 goroutine 没有必要吧

2022-01-19 07:17 UTC, jschwinger233 commented on rpc/rpc.go
> +		data.Data = req.Chunk.Data
这里的转换放到 rpc/transform.go里

2022-01-19 07:17 UTC, jschwinger233 commented on rpc/rpc.go
> +		data.Data = req.Chunk.Data
这里复用了同一个 data 可能会造成 race, 在 dc 的读端读取一个 data 之后还没来得及做处理就被下一个 data 的数据覆盖. 所以应该每次 new 一个新的

2022-01-19 07:17 UTC, jschwinger233 commented on rpc/rpc.go
> +	for m := range ch {
这里读写同步可能会死锁吧, 代码逻辑是先读所有请求, 发给 dc, 发完之后才去消费 ch, 所以可能阻塞在 dc <- data 这一步

2022-01-19 07:17 UTC, jschwinger233 commented on engine/docker/container.go
> +			logrus.Debugf("[VirtualizationCopyChunkTo] write header done, target: %s, id: %s", target, ID)
日志太多了...在重要 IO 的地方才加日志

2022-01-19 07:17 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +func (c *Calcium) doSendChunkFileToWorkload(ctx context.Context, engine engine.API, ID, name string, content io.Reader, uid, gid int, mode int64) error {
这一层封装好像没必要

2022-01-19 07:17 UTC, jschwinger233 commented on engine/docker/container.go
> +				data := make([]byte, 10 * 1024 * 1024)
没必要这么大的 buf 吧- - 小一点慢慢读就行了

2022-01-19 07:17 UTC, jschwinger233 commented on engine/docker/container.go
> +	utils.SentryGo(func(writer io.Writer, reader io.Reader) func() {
这个直接用无参数闭包就行了

2022-01-19 07:17 UTC, jschwinger233 commented on engine/docker/container.go
> +					err := writer.(*io.PipeWriter).Close()
用无参数闭包, 这里就不用做类型转换了

2022-01-19 07:18 UTC, jschwinger233 commented
要是有问题可以开个 zoom 来讨论

2022-02-01 07:23 UTC, lianghongji commented
我改了下代码，现在看起来是能够跑了。但是会有些比较诡异的情况，时而成功时而失败，让我再debug一下。然后关于上面的review意见我也再改一下。

2022-02-01 07:30 UTC, lianghongji commented on engine/docker/container.go
> +			logrus.Debugf("[VirtualizationCopyChunkTo] write header done, target: %s, id: %s", target, ID)
这些属于debug的，后面都会删掉

2022-02-17 13:47 UTC, jschwinger233 requested changes
自己多测试一下, 包括老的 Send 接口是否还能用, 还有发送一些 >3G 的文件, 都是我们真实存在的业务场景.

2022-02-17 13:47 UTC, jschwinger233 commented on rpc/rpc.go
> +	dc := make(chan *types.SendLargeFileOptions, 0)
直接 make(chan xx)

2022-02-17 13:47 UTC, jschwinger233 commented on rpc/rpc.go
> +	<- waitCh
这个同步好像没有必要, 只要让 596L-612L 和 614L-624L 交换一下, 把 server.Recv() 放到 goroutine. 这是因为我们通常是让下游等待上游, 而上游结束后自然会通过 close(ch) 让下游也结束.

2022-02-17 13:47 UTC, jschwinger233 commented on types/options.go
> +	FileChunkOptions
这个封装好像没有必要, 没有提升可读性, 也没有让程序更干净. 一个 chunk []byte 字段已经有不错的可读性, 而分拆的两个类型也并没有被单独用到.

2022-02-17 13:47 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +func (c *Calcium) newWorkloadExecutor(ctx context.Context, ID string, resp chan *types.SendMessage, wg *sync.WaitGroup) chan *types.SendLargeFileOptions {
这个函数名字不好, 名字叫 newExecutor 听起来像是一个很轻量级的初始化操作, 貌似最后返回一个 Executor 对象, 结果返回一个 chan 还有很多很重的 IO.

2022-02-17 13:47 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +			if preFile == "" || preFile != curFile {
直接禁止这种传到一半换 dst 的行为吧, 直接报错.

2022-02-17 13:47 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +						if err := c.withWorkloadLocked(ctx, ID, func(ctx context.Context, workload *types.Workload) error {
每个 chunk 都上一次锁, 虽然临界区是小了, 但是代价可能有点大. 考虑下从头到尾只上一把大锁, 传个大文件(>1G)对比一下耗时.

2022-02-17 13:47 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +			writerMap[curFile].Write(data.Data)
如果禁止了多重 dst 的请求就不需要 writerMap 了

2022-02-17 13:47 UTC, jschwinger233 commented on engine/docker/container.go
> +	const maxChunkSize = 2 << 10
放到 global

2022-02-17 13:47 UTC, jschwinger233 commented on engine/engine.go
> +	VirtualizationCopyChunkTo(ctx context.Context, ID, target string, size int64, content io.Reader, uid, gid int, mode int64) error
CopyTo 和 CopyChunkTo 可以合并吧, 让 cluster.Copy 和 cluster.CopyLarge 都调用一个 engine 接口

2022-02-17 13:47 UTC, jschwinger233 commented on engine/docker/container.go
> +	tw := tar.NewWriter(pw)
这里用 io.Pipe 用得很好, 我本来想的是用 tmpfile 落地磁盘. 这里用 pipe 虽然还是在内存, 但是并发地交给了 docker client 发送出去, 因此应该不会积压全部文件内容在内存.

2022-02-17 14:41 UTC, jschwinger233 commented on engine/engine.go
> +	VirtualizationCopyChunkTo(ctx context.Context, ID, target string, size int64, content io.Reader, uid, gid int, mode int64) error
刚才简单讨论了一下, rpc 层还是两个 API, 但是 cluster 层和 engine 都只有一个 send 接口.

2022-03-07 07:03 UTC, jschwinger233 requested changes

2022-03-07 07:03 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +			if err := data.Validate(); err != nil {
Validate() 放在 rpc 层的 toSendLargeFileOptions 里, toSendLargeFileOptions() (Options, error)

2022-03-07 07:03 UTC, jschwinger233 commented on cluster/calcium/sendlarge.go
> +func (c *Calcium) newWorkloadExecutor(ctx context.Context, ID string, resp chan *types.SendMessage, wg *sync.WaitGroup) chan *types.SendLargeFileOptions {
这个函数的切分做得不好, 我推荐这样做, 在 Calcium.SendLargeFile 里的调用改成

```go
for opt := range opts {
  for _, id := range data.Ids {
    sender := senders[id] or newSender()
    sender.send(data)
  }
}
```

代码细节自己补充, 具体实现和你目前的逻辑几乎一致, 只是把封装改了改.

2023-07-11 03:52 UTC, CMGS commented
unbelievable

2023-07-24 02:23 UTC, CMGS commented on rpc/rpc.go
> +			close(dc)
defer

2023-07-24 02:24 UTC, CMGS commented on rpc/rpc.go
> +		close(inputChan)
defer

2023-07-31 04:03 UTC, CMGS commented
resolve conflicts.

2023-08-07 06:04 UTC, CMGS commented on engine/docker/container.go
> +				err := pw.Close()
这个 err 的作用域是 Close 的 if 吧，最好一行来控制作用域，不要覆盖外层的 err

2023-08-07 06:04 UTC, CMGS commented on engine/docker/container.go
> +				if err != nil {
1

2023-08-07 06:05 UTC, CMGS commented on engine/docker/container.go
> +				if err != io.EOF {
如果是 EOF 就少打个日志？逻辑不太对吧

2023-08-18 06:35 UTC, CMGS commented on engine/docker/container.go
> +					return closeErr
```
if err:= pw.Close(); err!= nil {
  ...
}
```

2023-08-18 06:36 UTC, CMGS commented on engine/docker/container.go
> +					return closeErr
or you can
```
err:=pw.Close()
if err!= nil {
    log...
}
return err
```

2023-08-18 06:39 UTC, CMGS commented on rpc/rpc.go
> +func (v *Vibranium) SendLargeFile(server pb.CoreRPC_SendLargeFileServer) error {
一般这里变量叫 stream，和之前统一

2023-08-18 06:41 UTC, CMGS commented on cluster/calcium/sendlarge.go
> +					wg.Add(1)
我觉得这个 wg 得包进 workloadSender 里面

2023-08-18 06:42 UTC, CMGS commented
另外注意一下单元测试覆盖率和实际测试下多路文件并发 send

2023-09-07 06:38 UTC, merged