ResizeWindow support vm guest console multiplexing
projecteru2/core pull request #562
Opened 2022-03-11 11:06 UTC by wuleiaty

add a `execID` return value for `Execute` interface to support VM console multiplexing

2022-03-11 13:56 UTC, CMGS commented on go.mod
> +	github.com/projecteru2/libyavirt => /Users/lei.wu/go/src/libyavirt
这个不对吧

2022-03-13 13:47 UTC, jschwinger233 requested changes
原来的实现里  virt Execute 的 result string 语义是 pid, 直接把这个换成 execID 就行啦吧

2022-03-13 13:47 UTC, jschwinger233 commented on engine/engine.go
> +	Execute(ctx context.Context, ID string, config *enginetypes.ExecConfig) (execID string, result string, stdout, stderr io.ReadCloser, stdin io.WriteCloser, err error)
原来的接口里返回的 result string 是不是就是 execID 的语义? 是的话就不必再加返回参数了

2022-03-13 14:46 UTC, wuleiaty commented on go.mod
> +	github.com/projecteru2/libyavirt => /Users/lei.wu/go/src/libyavirt
这个忘了删了。。

2022-03-13 14:56 UTC, wuleiaty commented on engine/engine.go
> +	Execute(ctx context.Context, ID string, config *enginetypes.ExecConfig) (execID string, result string, stdout, stderr io.ReadCloser, stdin io.WriteCloser, err error)
之前这个[exitCode](https://github.com/projecteru2/core/pull/477)的pr里看起来是把之前的execID的语义改成了pid，然后virt的`ExecExitCode`方法用到了这个pid，感觉还是需要加一个execID

2022-03-13 15:01 UTC, jschwinger233 commented on engine/engine.go
> +	Execute(ctx context.Context, ID string, config *enginetypes.ExecConfig) (execID string, result string, stdout, stderr io.ReadCloser, stdin io.WriteCloser, err error)
我觉得可以直接对 virt 的 execID 赋予多重内涵，既包括 pid，也包含 (steam id / console id) (看你喜欢哪个名字)
不过这是 virt 的实现细节，对 ExecExitCode API 来说，用 execID 去拿退出码是合理的。

2022-03-13 15:19 UTC, wuleiaty commented on engine/engine.go
> +	Execute(ctx context.Context, ID string, config *enginetypes.ExecConfig) (execID string, result string, stdout, stderr io.ReadCloser, stdin io.WriteCloser, err error)
有道理！tql

2022-03-15 09:13 UTC, wuleiaty commented on engine/engine.go
> +	Execute(ctx context.Context, ID string, config *enginetypes.ExecConfig) (execID string, result string, stdout, stderr io.ReadCloser, stdin io.WriteCloser, err error)
更新了代码，保持了原来的接口设计

2022-03-16 04:00 UTC, jschwinger233 requested changes

2022-03-16 04:00 UTC, jschwinger233 commented on engine/virt/virt.go
> +func (v *Virt) ExecExitCode(ctx context.Context, ID, result string) (code int, err error) {
为啥这变量名还叫 result, 应该统一成 execID 吧

2022-03-16 04:00 UTC, jschwinger233 commented on engine/virt/virt.go
> +func (v *Virt) ExecResize(ctx context.Context, ID, result string, height, width uint) (err error) {
ExecResize 这个接口还需要同时传入 workloadID + execID 吗, 反正 docker 的实现只需要 execID, 如果 yavirt 也是只需要 execID, 那就改改 interface, 只传入 execID.

2022-03-16 04:00 UTC, jschwinger233 commented on engine/virt/virt.go
> +func (v *Virt) ExecResize(ctx context.Context, ID, result string, height, width uint) (err error) {
ExecResize 这个接口还需要同时传入 workloadID + execID 吗, 反正 docker 的实现只需要 execID, 如果 yavirt 也是只需要 execID, 那就改改 interface, 只传入 execID.

2022-03-16 04:00 UTC, jschwinger233 commented on engine/virt/virt.go
> +func (v *Virt) ExecResize(ctx context.Context, ID, result string, height, width uint) (err error) {
另外把所有的 result 变量名都改改. 之前用 result 是因为在不同的 engine 实现下有不同的语义, 现在都统一为 execID 就统一名字.

2022-03-16 04:00 UTC, jschwinger233 commented on engine/virt/virt.go
> +func (v *Virt) ExecResize(ctx context.Context, ID, result string, height, width uint) (err error) {
另外把所有的 result 变量名都改改. 之前用 result 是因为在不同的 engine 实现下有不同的语义, 现在都统一为 execID 就统一名字.

2022-03-16 08:40 UTC, wuleiaty commented on engine/virt/virt.go
> +func (v *Virt) ExecResize(ctx context.Context, ID, result string, height, width uint) (err error) {
virt的ExecResize也不需要传workloadID了，改了下

2022-03-16 08:55 UTC, jschwinger233 commented on engine/virt/virt.go
> +func (v *Virt) ExecExitCode(ctx context.Context, ID, result string) (code int, err error) {
为啥这变量名还叫 result, 应该统一成 execID 吧

2022-03-16 08:55 UTC, jschwinger233 commented on engine/engine.go
> +	ExecExitCode(ctx context.Context, ID, execID string) (int, error)
其实这个 ExecExitCode 也有点碍眼, 你看 ExecResize 只需要 execID, 而 ExitCode 就需要 ID + execID. 不过要是不好改就这样吧.

2022-03-16 08:57 UTC, jschwinger233 approved these changes

2022-03-17 03:22 UTC, wuleiaty commented on engine/engine.go
> +	ExecExitCode(ctx context.Context, ID, execID string) (int, error)
嗯ExecExitCode的yavirt实现需要这两个参数

2022-03-31 10:24 UTC, DuodenumL commented
LGTM！就是需要解决一下冲突，以及能不能rebase一下，变成1个commit...

2022-04-04 04:47 UTC, CMGS commented
conflict 了要 rebase

2022-04-04 09:05 UTC, merged