feat: storage allocation
projecteru2/core pull request #91
Opened 2019-06-18 05:52 UTC by anrs

2019-06-18 06:48 UTC, CMGS requested changes

2019-06-18 06:48 UTC, CMGS commented on Makefile
> +	go test -count=1 -cover ./utils/... ./types/... ./store/etcdv3/... ./scheduler/complex/...  ./source/common/... ./lock/etcdlock/... ./auth/simple/... ./cluster/calcium/...
为啥 count 1

2019-06-18 06:48 UTC, CMGS commented on scheduler/complex/potassium.go
> +	leng := len(nodesInfo)
你这种奇怪的命名。。

2019-06-18 06:48 UTC, CMGS commented on scheduler/complex/potassium.go
> +		nodesInfo[i].Capacity = utils.Min(storCap, nodesInfo[i].Capacity)
这里你用 min 函数，为啥外层要用 select 来判断。。

2019-06-18 06:48 UTC, CMGS commented on types/node.go
> +	StorageUsage float64 // Current storage usage ratio
能不能。。。都中文或者都英文

2019-06-18 06:48 UTC, CMGS commented on rpc/gen/core.proto
> +	int64 storage = 13;
你们 emacs 都不对齐的么

2019-06-18 06:49 UTC, CMGS commented
还有，改版本号……
记得 merge 主干

2019-06-19 08:28 UTC, anrs commented on Makefile
> +	go test -count=1 -cover ./utils/... ./types/... ./store/etcdv3/... ./scheduler/complex/...  ./source/common/... ./lock/etcdlock/... ./auth/simple/... ./cluster/calcium/...
equivalent to "GOCACHE=off go test"

2019-06-19 08:28 UTC, anrs commented on scheduler/complex/potassium.go
> +	leng := len(nodesInfo)
local vars lah

2019-06-19 08:30 UTC, anrs commented on types/node.go
> +	StorageUsage float64 // Current storage usage ratio
it doesn't matter lah.

2019-06-19 08:31 UTC, anrs commented on rpc/gen/core.proto
> +	int64 storage = 13;
resolved

2019-06-19 08:44 UTC, anrs commented on scheduler/complex/potassium.go
> +		nodesInfo[i].Capacity = utils.Min(storCap, nodesInfo[i].Capacity)
resloved

2019-06-19 15:40 UTC, CMGS commented on types/node.go
> +	switch {
switch 爱好者。。

2019-06-19 15:44 UTC, CMGS commented on types/config.go
> +	// The max int32 value.
注释有毛病啊

2019-06-20 02:17 UTC, anrs commented on types/config.go
> +	// The max int32 value.
???

2019-06-20 02:18 UTC, anrs commented on types/node.go
> +	switch {
lol

2019-06-20 06:30 UTC, CMGS approved these changes

2019-06-20 06:36 UTC, CMGS commented on rpc/gen/core.proto
> +	map<string, double> storage_percents = 6;
WTF

2019-06-20 06:36 UTC, CMGS commented on rpc/gen/core.proto
> +	double storage_percent = 6;
WTF2

2019-06-20 06:45 UTC, anrs commented on rpc/gen/core.proto
> +	map<string, double> storage_percents = 6;
resolved

2019-06-20 06:46 UTC, anrs commented on rpc/gen/core.proto
> +	double storage_percent = 6;
resolved

2019-06-20 06:52 UTC, merged